### ISSUE TITLE
Clicking into detail tables requires you to click on the text of the dimension name

### ISSUE THREAD

**Issue by djbarnwal** [rilldata/rill-developer#1027]
You should be able to open the detail page by clicking anywhere but the three dot menu

**Comment by bcolloran** [comment]
I don't think this behavior (opening the dimension table by clicking anywhere in the header) is actually is actually optimal now that we have the three dots menu, because the three dots menu is such a tiny interaction target-- It's easy to miss the three dots menu when you're trying to click on it and to be sent into the dimension table, which can be very disorienting. I would recommend adding A small exclusion area around the three dots menu to create a bit of extra space-- for example a div that goes behind the that is the full height of the header and is equally wide.

**Comment by magorlick** [comment]
Yes, not literally just the three dots- a meaningful area around that icon that is easy to click on for the menu.

**Comment by hamilton** [comment]
This is precisely what the `IconButton` is for. Let's utilize that.
