### ISSUE TITLE
Horizontal scroll on output table is janky

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#1072]
If you try to scroll left-to-right you literally can't if you do it quickly. It always springs back to the default position. This makes the output much less useful.

**Comment by bcolloran** [comment]
I wonder if this is related to the scrolling bug I filed at https://github.com/rilldata/rill-developer/issues/1046, which also had a strange scroll speed dependence. I think what I was seeing probably had something to do with the DOM virtualization, and I wouldn't be surprised if this is related to that as well.

**Comment by hamilton** [comment]
I"ll take a crack at this but may loop in @djbarnwal

**Comment by djbarnwal** [comment]
I am unable to reproduce the issue here. The scrollbar is where I want it to be. The data points sometime take a sec to appear but I think that's a side effect of using virtualized tables.
[Kapture 2022-11-07 at 15.09.39.webm](https://user-images.githubusercontent.com/4402679/200278102-fddf558c-fb5b-47ba-a4fb-2f91cdede648.webm)

**Comment by djbarnwal** [comment]
For me the jankiness is present when the model is in `running` state. I suspect what is happening is that the props for `PreviewTable` are being updated frequently while the model is running. This leads to re-rendering of the table as column profile data points are being hydrated. Any changes here will be moot as we would be adopting API based approach soon. Will revisit this when we have APIs for Column profiles and preview tables integrated.
