### ISSUE TITLE
Better Metric Formatting - Opinionated formats aren’t always helping people understand their data quickly.

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#1163]
Money - When I have formatting for USD I should Always see 2 decimal places to help with visual alignment and scanning. 

![Image](https://user-images.githubusercontent.com/5587788/199257501-c276741e-cd6c-4da0-8383-f81a82de86b6.png)

Humanized - When I have a very big outlier humanizing the numbers makes them meaningless because we only use the biggest number to determine what units we will show. We should reconsider our heuristic.  _After looking at this again on the detail table I am wondering if we have had a regression - do we truncate numbers that are "humanized" and add their units in the detail table or did this heuristic change? In the past everything but the heaviest hitting outlier was `<1K` or something like that where you couldn't tell what was going on unless you hovered._

![Image](https://user-images.githubusercontent.com/5587788/199258343-67f1672d-2536-4437-88f6-14eef3ce4e53.png)

**Comment by djbarnwal** [comment]
Thanks for opening the issue @magorlick 
I think the current implementation is not very ideal. Some of the problems which I have noticed are (in addition to the above mentioned ones) - 

**1. The output results are not deterministic** 
So how the algorithm works now is that it tries to find an optimal scale and applies it to the whole leaderboard. Now to make things faster we are using a heuristic where we take the first 5 dimensions as sample and try to find a scale. This works in principle but often times you would get different scale for the same leaderboard with same timegrain. This happens because of where your scroll position is when the leaderboards are being rendered. A better solution would be to always have the same scale for a given leaderboard and timeframe.

**2. Lack of support for other currency formats**
We need a way to take secondary level of input for our formatting (choosing currency, scale for humanize etc.). Going with defaults is okay for now but as we scale we would have to support multiple formatting options. We need to find the right balance between expressivity and defaults. Defining a set of affordances can be helpful in guiding where we want this to go.

**Comment by magorlick** [comment]
PRD: https://www.notion.so/rilldata/Dashboard-formatting-8a4882834f0f4ac7aa4e584fae40f4b9
