### ISSUE TITLE
Runtime: Handle large query results gracefully

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill-developer#1211]
Today, the runtime server is configured to allow a maximum message size of 4MB (except for file uploads). This means that queries that return more than 4MB of raw data in one request will emit an error:
```
grpc: received message larger than max (26683905 vs. 4194304)
```

This isn't great for two reasons:
- The error message is not very informative.
- Checking response size on the networking layer is too late in the call chain. At this point, the full query result (which could be GBs) has wastefully been loaded into memory.

Questions to answer:
1. Is 4MB a reasonable max response size for one HTTP request? If not, what should it be?
2. Should we also add a row limit for queries? E.g. a round number like 10000 rows in one request
3. Currently, paging is a client responsibility (using `LIMIT` and `OFFSET`). Should we investigate adding paging to the query endpoint instead (see example [here](https://cloud.google.com/apis/design/design_patterns#list_pagination))?
    - This requires further engineering investigation. Naively, the options are:
        - Caching the database cursor for a duration of time (we'd have to investigate the DB performance implications)
        - Injecting a `LIMIT` + `OFFSET` clause in queries (not sure if that's possible in the general case)

Task list (so far):
- [ ] Prevent loading large query results into memory by checking the result size when paging through the database cursor. Return a friendlier error as soon as the result size exceeds the limit.

**Comment by hamilton** [comment]
Discussed over slack, but to resurface the thinking here:, as a rule, we should never return this much data to the application. Almost all tools like Rill Developer return just enough of a representation of the data that users can make decisions. Despite this, there may be cases where we have bugs surface due to a large result set accidentally getting sent over the wire.

So with this in mind, I think it'd be good to solve for the case where the application doesn't do the right thing, a user can report the error. I think the task then becomes to provide more informative errors to protect for this case that we can surface in the CLI + interface

**Comment by magorlick** [comment]
relates to: https://github.com/rilldata/rill-developer/issues/1081

**Comment by hamilton** [comment]
I think the only case where we might actually return a big result set, and this is worth checking today, is on export?

**Comment by esevastyanov** [comment]
Here is a [notion page](https://www.notion.so/rilldata/Handle-large-query-results-gracefully-8ebe34ceed5b430abc883fffeb36e374) dedicated to the ticket @begelundmuller

**Comment by begelundmuller** [comment]
Given the discovery in the Notion doc, closing this issue and will use https://github.com/rilldata/rill-developer/issues/2333 for tracking implementation
