### ISSUE TITLE
Runtime: Support editing and deleting instances

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill-developer#1778]
The runtime currently has `CreateInstance` and `DeleteInstance` RPCs. The `DeleteInstance` RPC is not fully implemented, however, e.g. it does not clear caches or drop the `.db` file. 

We also need one or more new RPCs for editing instances. Initially, I would favor flexibility and allow editing both OLAP drivers/DSNs, repo drivers/DSNs, and env vars.

Task list:

- [ ] Add an `EditInstance` RPC (or consider if it makes more sense to split it into multiple)
- [ ] Improve the `DeleteInstance` RPC by ensuring a correct implementation
- [ ] Add an option to the `DeleteInstance` RPC for dropping the DB (will probably also require a new function on the `runtime/drivers.OLAPStore` interface.

**Comment by k-anshul** [comment]
@begelundmuller If we change OLAP drivers/DSNs should we close existing connection as well ? 
I think we should otherwise we might leak connections. I am favouring patch API for edit instance for this reason.

**Comment by begelundmuller** [comment]
About closing connections, I think we should make a best effort to close connections (but not rely on it). The connection cache is an LRU, so connections will in theory be evicted. It might make sense to add a timeout as well to prevent keeping stale handles open forever (if the LRU is large).

The caching isn't great though. I also notice the `catalogCache` uses a `map`, which would never evict items (and the `catalog.Service` keeps pointers to connections...). Definitely feel free to improve some of the lifecycle management here.

Thinking ahead to hosting, when the runtime is distributed, we can never be sure all machines have closed their connections. But if the cache is indexed by DSN (or hash of DSN) or something like that, then LRUs would ensure eventual cleanup.

**Comment by k-anshul** [comment]
Here is my take on the current DB interactions in our code:
1. [sql.OpenDB](https://github.com/golang/go/blob/e7cfcda67d430a6e3cf4e8dfef27416870a2b007/src/database/sql/sql.go#L781) doesn't open any connection to underlying database and just creates a DB handler so we are essentially not creating any connection to db till we run any query although we would still want to close the db handler.
2. This may not be true in case we are using some third party extension. For eg : [sqlx.Connect ](https://github.com/jmoiron/sqlx/blob/28212d434cdd87418ecd0cb81173690ce7ac6ab6/sqlx.go#L642)runs a ping query to verify db which would mean it creates one connection on open itself.
3. None of the actual db connections are managed by us. They are all managed by these db handlers.
4. We would want to close all db handlers before application stops to free up connections on db servers. On cloud a few continuously restarting servers can keep on opening connections to underlying DB and may even choke the db server.
5. We would also want to close db handlers on edit instance for the same reason as above plus doing other cleanups in db handlers like closing channels, stopping go routines etc.

Based on this I would like to propose few changes to how db connections are handled right now:
1. I think we should rename [Connection](https://github.com/rilldata/rill-developer/blob/c3a7d8e2ccc6ab385c67f6d18b25213309ba1a43/runtime/drivers/drivers.go#L47) interface in `drivers.go` to something like `Connector` or `DBhandler` or even `DB`. This is creating lot of confusion since its not a typical db connection which are still handled by underlying databases (`sql.DB` or `sqlx.DB`). This also has typical characteristics of a db handler rather than that of db connection like we don't have to worry about closing these on a timeout and can keep it open throughout the lifecycle of our application.
2. The `migrate` method in current `connection` interface can also be removed and made part of Open itself. From what I could see it is just creating some tables and running alters which should be done once on opening db handler.
3. The `connectionCache` can be removed and we should just be maintaining a `catalogCache`. This catalogCache needs to be updated on `instance` mutations only and all db handlers can be closed safely on application stop.
4. All the other pieces of the code should not open db handlers and all interactions should be done via `catalog.Service` returned from catalogCache. It can be made into a LRU cache. It doesn't have to implement time based eviction policies but can implement to remove open db handlers for older unused instances.
6. With these changes in place I see no reason for maintaining current `Connection` interface. All the interactions can be done with `stores` itself. We should ensure that correct stores are populated while creating service for an instanceID.

**Comment by begelundmuller** [comment]
> 4. We would want to close all db handlers before application stops to free up connections on db servers. On cloud a few continuously restarting servers can keep on opening connections to underlying DB and may even choke the db server.

In `runtime/runtime.go` in `Close()` (which should be run on exit) it closes all open connections (except, I see, the metastore – fixed here: https://github.com/rilldata/rill-developer/pull/1808).

> 5. We would also want to close db handlers on edit instance for the same reason as above plus doing other cleanups in db handlers like closing channels, stopping go routines etc.

Yes – right now there should not be any go routines running per instance. When we introduce "controllers" (for reconcile) soon, we'll have that, though. Generally, such cleanup should happen when calling `Close` on an object.

> 1. I think we should rename [Connection](https://github.com/rilldata/rill-developer/blob/c3a7d8e2ccc6ab385c67f6d18b25213309ba1a43/runtime/drivers/drivers.go#L47) interface in `drivers.go` to something like `Connector` or `DBhandler` or even `DB`. This is creating lot of confusion since its not a typical db connection which are still handled by underlying databases (`sql.DB` or `sqlx.DB`). This also has typical characteristics of a db handler rather than that of db connection like we don't have to worry about closing these on a timeout and can keep it open throughout the lifecycle of our application.

I agree, I would suggest `Handle` or `Store` though (since `Connector` would interfere with sources terminology, and `DB` is strained for drivers like `file` and `git`). If you think this will take more than a few hours to refactor, though, then we should probably do this later (not urgent).

This reminds me that you should also know about https://github.com/rilldata/rill-developer/issues/1519 (currently in backlog). Might be helpful for you as context, maybe you'll even want to do some of it now. 

> 2. The `migrate` method in current `connection` interface can also be removed and made part of Open itself. From what I could see it is just creating some tables and running alters which should be done once on opening db handler.

Currently they'll run at the same time, but we might need it separate, so let's keep it this way. In production, it's not uncommon to run migrations separately – it has some advantages, like not needing service accounts with DDL permissions on public-facing endpoints, and better insight/control over how migrations run.

> 3. The `connectionCache` can be removed and we should just be maintaining a `catalogCache`. This catalogCache needs to be updated on `instance` mutations only and all db handlers can be closed safely on application stop.

Currently, the `connectionCache` is used directly by some endpoints (like all analytical API queries), and also used to populate `catalogCache`. But I agree that it feels like this should be streamlined.

Note that multiple instances (which `catalog.Service` basically represents) can use the same connections in some cases (will especially be the case for shared connections, like `CatalogStore` in cloud will be). So keeping these separate might still make sense. Not sure I have a good proposal right now, just highlighting some complexities. Let me know what you think.

> 4. All the other pieces of the code should not open db handlers and all interactions should be done via `catalog.Service` returned from catalogCache. It can be made into a LRU cache. It doesn't have to implement time based eviction policies but can implement to remove open db handlers for older unused instances.

I agree it feels like it would make sense to streamline around a common entrypoint for an instance, but make a dedicated one in the `runtime` package instead of using `catalog.Service` directly (it could wrap `catalog.Service`, but we'll deprecate it when doing the reconcile refactor soon). 

I still wonder if connections should be a separate layer, due to the composability (and also, imagine an instance just uses the OLAP store, then we don't want to keep the others open). I know in theory the underlying driver might also keep a connection pool and have timeouts, but we shouldn't rely on that (e.g. the `database/sql` package will keep at least one connection open all the time).

> 5. With these changes in place I see no reason for maintaining current `Connection` interface. All the interactions can be done with `stores` itself. We should ensure that correct stores are populated while creating service for an instanceID.

It will still need the `Connection` interface (or whatever we rename it to) because one connection can be used for multiple stores. E.g. a Postgres database could be used as both a registry and catalog (and if we enabled cloud modeling, we might also use it as a "repo" to virtualize a file system). Linking this again for context: https://github.com/rilldata/rill-developer/issues/1519

**Comment by k-anshul** [comment]
> Yes – right now there should not be any go routines running per instance. When we introduce "controllers" (for reconcile) soon, we'll have that, though. Generally, such cleanup should happen when calling Close on an object.

Actually what I meant here was related to cleanup within these db handlers that we get from `sql.Open` package. Nothing wrt our application code.

> Currently, the connectionCache is used directly by some endpoints (like all analytical API queries), and also used to populate catalogCache. But I agree that it feels like this should be streamlined.

This reminds me that these APIs repeatedly query instance information from metadata DB which is okay for local application but would definitely cause issues when metadata DB will be postgres. So we would want to remove the usage from those APIs as well. 

> Note that multiple instances (which catalog.Service basically represents) can use the same connections in some cases (will especially be the case for shared connections, like CatalogStore in cloud will be). So keeping these separate might still make sense. Not sure I have a good proposal right now, just highlighting some complexities. Let me know what you think.

Yeah agreed. What I was thinking was that actually the stores should maintain their own db handlers (by db handler I mean the db handler that we get from `sql.OpenDB`). In that case the store can take care of whether the db handler is a singleton or instance specific. This is very similar to what you are also proposing in #1519. On deletion/edit of an instance this should be notified to the store so the store can take decision on whether to close the handler. This is similar to returning a connection back to the pool.
**Note** : This would mean that we keep different handler and in turn different db connections for different stores even though they use same underlying database.

> I agree it feels like it would make sense to streamline around a common entrypoint for an instance, but make a dedicated one in the runtime package instead of using catalog.Service directly (it could wrap catalog.Service, but we'll deprecate it when doing the reconcile refactor soon).

With the above change its just a matter of getting an appropriate handler from store.

> I still wonder if connections should be a separate layer, due to the composability (and also, imagine an instance just uses the OLAP store, then we don't want to keep the others open).

With stores maintaining their own handlers this should also be addressed.

> I know in theory the underlying driver might also keep a connection pool and have timeouts, but we shouldn't rely on that

I am not sure if I correctly understand this. We are not maintaining any actual db connections and as long as we have a db handler open we will be able to run a query (either on pooled connection or new).

> It will still need the Connection interface (or whatever we rename it to) because one connection can be used for multiple stores.
Keeping one connection(handler) for multiple store has its own advantages as well as disadvantages. Advantages being that in theory it would mean opening less number of actual db connections. However on a hosted environment with multiple instance running simultaneous APIs I can differently picture the db handler using multiple tcp connections internally. Keeping two separate db handlers would mean dividing these tcp connections among two handlers.

**Comment by k-anshul** [comment]
> Actually what I meant here was related to cleanup within these db handlers that we get from sql.Open package. Nothing wrt our application code.

One example of this is that we open a db handler during `CreateInstance` API. That db handler is never closed. Also since we are running some migrations as well. It would mean we are also not closing the db connection which is also never closed.

**Comment by begelundmuller** [comment]
Thanks for these thoughts.

I'm a little worried about redundantly creating `sql.DB` objects – they have a built-in connection pool, will mostly always keep at least one connection alive, run various goroutines, might do heartbeats, etc. Also, some DBs (like Postgres) support only a limited number of connection, so this might quickly exhaust that. If we open multiple DB handles to the same database, we're essentially creating a pool of pools, which seems like an anti-pattern. By having one handle, it can be maximally efficient on connection spawning/closing, caching, heartbeats, rate limits, etc.

However, in practice this will mostly be a problem for the "shared infra" (using the terminology of https://github.com/rilldata/rill-developer/issues/1519). If we can make sure we don't create such connections per instance, then I think it's okay if we create new connections per instance.

I'm not sure if you're also suggesting that each repo/olap/catalog/etc. is created as a separate handle. I don't think that would work, one handle should be able to serve as multiple stores. For example, DuckDB has some limitations on open handles, and our DuckDB driver does some non-trivial logic to share/prioritize the connection pool amongst OLAP and catalog queries.

I think you're starting to have a sense of a solution here. IMO these are currently the requirements:

- Should only open handles for "shared" infra once (even if provided to instances, e.g. for a Postgres catalog)
- It's okay to open instance-specific infra handles once per instance (but not once per instance's OLAP/catalog/etc.)
- Should not redundantly open infra handles – i.e. if making an OLAP query, should not open repo store
- Should not redundantly keep infra handles open – i.e. if initially making a repo query, but then only making OLAP queries after, it should eventually close the repo store
- Should cache instance info for a duration (5 sec?) before doing a lookup in catalog again (since it's getting called quite a lot, as you point out)

Reflecting on the above, it seems to me a single pool of `drivers.Connection` objects, maintained in the `runtime.Runtime` object, could make sense. It would allow maximum re-use and eviction of unused connections, regardless of how they're composed into instances. The `catalog.Service` should then not keep pointers to these, but should request them from the pool each time it needs them. What do you think? 

Btw, about:

> One example of this is that we open a db handler during CreateInstance API. That db handler is never closed. Also since we are running some migrations as well. It would mean we are also closing the db connection which is also never closed.

This is definitely not good! We should fix that :)

**Comment by k-anshul** [comment]
Thanks for your clarifications and I agree that having store maintain their own handlers would cause more issues than it would solve and agree on maintaining a single pool of `drivers.Connection` objects.
Based on above suggestions I would like to propose few changes/additions to #1519 to implement the shared infra concpet.

-  I would keep a `reference` counter in the impl of `drivers.Connection`. This is to ensure that the underlying handler is only closed when last referencing instance closes the connection. The `driver` would maintain the shared `drivers.Connection` and would just increase `reference` basis `shared` flag passed in `open` so instance specific handlers would always have `reference` count as 1. 
I am picturing it something like this :

```
type connection struct {
	db        *sqlx.DB
	reference int
	mutex     sync.Mutex
	...
}
```
- The existing connectionCache in `runtime` remains as it is and should be cleared on edit/delete instances or on a timeout/cache size increase. I would prefer longer timeouts since [db handlers are expected to be long-lived.](https://github.com/golang/go/blob/e7cfcda67d430a6e3cf4e8dfef27416870a2b007/src/database/sql/sql.go#L874)
- I also propose removing the service cache (in order to not run into issues like underlying handler is closed but service cache is not cleared). The service can be constructed at a api request level for convenience if required. To do this efficiently, yes, an instance cache is also required.
- On runtime instantiation logic defined in #1519. I am unclear on how this can be used in current form. I am thinking something of below form should be easier to use  :
```
type ConnectOptions {
	Driver string
	DSN string
}

type runtime.InfraOptions struct {
	Registry: {Name: "metastore", DSN: "..."},
	Repo: {Name: "metastore", DSN: "..."}
}

type runtime.InstanceInfraOptions struct {
	OLAP: {Driver: "duckdb", DSN: "..."},
	Catalog: {Driver: "duckdb", DSN: "..."}
}
```
We may have to handle the special case of embedded catalogs though.

**Comment by k-anshul** [comment]
With the above changes in place, the suggestion noted in #1519:
> Refactor functions to accept an instance ID on instantiation instead of in sub-functions – i.e. make them c.CatalogStore(instanceID), c.OLAPStore(instanceID) and c.RepoStore(instanceID) and remove the instanceID parameter from their interface functions. The implementations should check shared before resolving and return an error for configurations they don't support. If shared is true and they support multi-instance mode, they should return a wrapped object containing the instance ID. 

This can be done for better abstractions but is not absolutely necessary.

**Comment by k-anshul** [comment]
On this suggestion of mine:
> The driver would maintain the shared drivers.Connection and would just increase reference basis shared flag passed in open so instance specific handlers would always have reference count as 1.

I think its okay to maintain this at runtime's cache itself and only close the handler on application close if you think it is unnecessarily complicating the impl.

**Comment by begelundmuller** [comment]
Some quick comments:

1. High-level, reference counting seems like the right approach. I don't think it should be implemented inside the object, though, rather the cache should keep track of references (so instead of something like `cache.Get(...)`, it would need something like `cache.Acquire(...)` followed by `defer cache.Release(...)`). 
2. Sounds good
3. Unfortunately, we can't really remove the service cache since it keeps some slightly intensive state (like the object DAG), that we can't recreate on each request when doing keystroke-by-keystroke modeling. Here's an alternative idea: maybe we could remove the references it holds to the stores though, and instead give it a reference to the `Runtime` object (or directly to the cache), and on each call to it, it would acquire/release a reference to the stores it needs.
4. This would warrant a separate discussion. Let's initially avoid doing that now.

**Comment by begelundmuller** [comment]
Closed by https://github.com/rilldata/rill-developer/pull/1811
