### ISSUE TITLE
Admin: Set/edit variables on projects and deployments

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill-developer#1920]
- [x] Add option for passing `-e/--env` on the `rill project connect` command
- [x] Add a `rill project env set PROJECT_NAME KEY VALUE` command
- [x] Add a `rill project env rm PROJECT_NAME KEY` command 

The above should correctly propagate to the underlying create/edit instance RPCs from the admin server to the runtime.

Questions to consider:

- Should we add a `rill project get` command?
- How can we support branch deploys where ENV vars are different on dev branches than prod branches?

**Comment by k-anshul** [comment]
@begelundmuller Do we want to trigger reconcile if envs are update(I think we should not)? In case no, do we want to add some command to manually redeploy the project, something like `rill project deploy PROJECT_NAME `

**Comment by begelundmuller** [comment]
@k-anshul, we don't want to automatically trigger that at this point.

We will support manual triggers of reconcile, refresh and reset from the CLI. Tracking it in this issue: https://github.com/rilldata/rill-developer/issues/1923

**Comment by k-anshul** [comment]
Rill project get command can be added since a user may be interested in checking current envs.
> How can we support branch deploys where ENV vars are different on dev branches than prod branches?

This is a trickier problem to solve and I think this can be better handled when we design for dev branches. IMO our current modelling may make it cumbersome to handle dev branches since user need to specify project name, branch name every time some modification/trigger/reconcile needs to be done. One idea could be to create child/sub projects for dev branches. But yeah this needs some dedicated discussions.

**Comment by begelundmuller** [comment]
Closed by https://github.com/rilldata/rill-developer/pull/1937
