### ISSUE TITLE
Leaderboard generated queries have additional order true that doesn't work well for druid

### ISSUE THREAD

**Issue by nishantmonu51** [rilldata/rill-developer#2054]
```
SELECT "dimension", sum(cnt) as "measure_0" FROM "datasource" WHERE 1=1 AND "__time" >= '2022' AND "__time" < '2024' AND ("daypart"  IN ('daytime'))  GROUP BY "datasource" ORDER BY true, "measure_0" DESC LIMIT 250
```
Above generated query has ORDER BY true, "measure_0", the query generated should have ORDER BY "measure_0" only.

**Comment by esevastyanov** [comment]
The query having `ORDER BY true` is explained by Druid as `"queryType": "groupBy"`
The query with no `ORDER BY true` is explained by Druid as `"queryType": "topN"`

In Druid, `topN` and `timeseries` queries are generally more efficient than groupBy queries. This is because the query engine for `topN` and `timeseries` has specific optimizations for single-dimension grouping and sorting use cases.
`topN` queries are designed for simple, single-dimension grouping and ordering scenarios. They can be faster and more memory-efficient than `groupBy` queries, but they may return approximate results, especially when working with large datasets or high cardinality dimensions. This trade-off between accuracy and performance is often acceptable for many use cases.

`timeseries` queries are optimized for time-based aggregations and filtering. They can efficiently handle time-based data and are typically faster than equivalent `groupBy` queries.

On the other hand, `groupBy` queries are more versatile and can handle more complex aggregation and ordering scenarios. They return exact results, but they can be slower and more resource-intensive than `topN` and `timeseries` queries.
