### ISSUE TITLE
add linting to the repository

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#214]
Marissa Gorlick 
May 4, 2022, 9:17 PM

Adopting eslint and prettier adding both at the same time.  Proposing going folder by folder to make changes.  Want to warn rather than fail and will clean up as we complete PRs.

We should prep this week and think about merging next week while folks are engaged in the Global All Hands.

Edit

Delete

Hamilton Ulmer 
April 27, 2022, 8:29 PM
Brendan Colloran turns out we had a ticket for this :)

**Comment by hamilton** [comment]
Would it be possible to kick this to after we have a review + merge of #201?

**Comment by bcolloran** [comment]
> Would it be possible to kick this to after we have a review + merge of #201?

@hamilton it's already underway and PR filed yesterday: #264 :-)

That PR actually disables most of the onerous rules (the ones that are violated very frequently). I've taken on the chore of doing some of the clean up in the existing code (just the low hanging fruit, rules that only had a couple failures each)

I don't actually think this should impose much overhead; there might be a couple merge conflicts, but you're mostly working in different files than the ones I updated. And since I've disabled all the rules where we have a lot of failures, I don't think you'll need to fix more than a couple lint errors in your new code (any rules activated by #264 represent code patterns that did not come up a lot in our code base).
