### ISSUE TITLE
CLI: Don't print CLI usage for common errors

### ISSUE THREAD

**Issue by nishantmonu51** [rilldata/rill-developer#2176]
e.g. user clicks on reject in the login flow. 
We also print the error message twice.

**Comment by nishantmonu51** [comment]
+cc @jkhwu

**Comment by k-anshul** [comment]
Following options can be taken:
1. Silence printing help and only print the error. 
![image](https://user-images.githubusercontent.com/12948312/234591022-00b44172-83c7-4f31-854d-b5c1e8376731.png)
Please note the help will still be printed if missing mandatory arguments/flags. This can also be fixed with custom handlers, if required(as done in gh-cli).
2. Print the error message and a custom help message like `run project rename --help for further help`.
3. Separate all errors into client/internal errors and print help message only in client/common errors. It will be a tedious task to separate all the errors and it may not be feasible to do so in all cases.

**Comment by k-anshul** [comment]
We will go ahead with approach 1.
